INSERT INTO TASK_TYPES
(TASK_TYPE) VALUES
('one'),
('two');
SELECT * FROM TASK_TYPES;

INSERT INTO TASKS
(TASK_TYPE) VALUES
('one'),
('one');

SELECT * FROM TASK_IDS;
SELECT * FROM TASKS_PTA;
SELECT * FROM TASKS;

UPDATE TASKS
SET TASK_STATUS = 'I'
WHERE TASK_ID = 1
;

SELECT * FROM TASK_IDS;
SELECT * FROM TASKS_PTA;
SELECT * FROM TASKS;
